// Layer Shader Spv Data header
//
// This file is auto-generated by cmake, don't edit it.

static const uint32_t absval_spv_data[] = {
#include "absval.spv.hex.h"
};
static const uint32_t absval_fp16s_spv_data[] = {
#include "absval_fp16s.spv.hex.h"
};
static const uint32_t absval_fp16a_spv_data[] = {
#include "absval_fp16a.spv.hex.h"
};
static const uint32_t absval_pack4_spv_data[] = {
#include "absval_pack4.spv.hex.h"
};
static const uint32_t absval_pack4_fp16s_spv_data[] = {
#include "absval_pack4_fp16s.spv.hex.h"
};
static const uint32_t absval_pack4_fp16a_spv_data[] = {
#include "absval_pack4_fp16a.spv.hex.h"
};
static const uint32_t batchnorm_spv_data[] = {
#include "batchnorm.spv.hex.h"
};
static const uint32_t batchnorm_fp16s_spv_data[] = {
#include "batchnorm_fp16s.spv.hex.h"
};
static const uint32_t batchnorm_fp16a_spv_data[] = {
#include "batchnorm_fp16a.spv.hex.h"
};
static const uint32_t batchnorm_pack4_spv_data[] = {
#include "batchnorm_pack4.spv.hex.h"
};
static const uint32_t batchnorm_pack4_fp16s_spv_data[] = {
#include "batchnorm_pack4_fp16s.spv.hex.h"
};
static const uint32_t batchnorm_pack4_fp16a_spv_data[] = {
#include "batchnorm_pack4_fp16a.spv.hex.h"
};
static const uint32_t concat_spv_data[] = {
#include "concat.spv.hex.h"
};
static const uint32_t concat_fp16s_spv_data[] = {
#include "concat_fp16s.spv.hex.h"
};
static const uint32_t concat_fp16a_spv_data[] = {
#include "concat_fp16a.spv.hex.h"
};
static const uint32_t concat_pack4_spv_data[] = {
#include "concat_pack4.spv.hex.h"
};
static const uint32_t concat_pack4_fp16s_spv_data[] = {
#include "concat_pack4_fp16s.spv.hex.h"
};
static const uint32_t concat_pack4_fp16a_spv_data[] = {
#include "concat_pack4_fp16a.spv.hex.h"
};
static const uint32_t concat_pack4to1_spv_data[] = {
#include "concat_pack4to1.spv.hex.h"
};
static const uint32_t concat_pack4to1_fp16s_spv_data[] = {
#include "concat_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t concat_pack4to1_fp16a_spv_data[] = {
#include "concat_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t convolution_spv_data[] = {
#include "convolution.spv.hex.h"
};
static const uint32_t convolution_fp16s_spv_data[] = {
#include "convolution_fp16s.spv.hex.h"
};
static const uint32_t convolution_fp16a_spv_data[] = {
#include "convolution_fp16a.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_spv_data[] = {
#include "convolution_1x1s1d1.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_fp16s_spv_data[] = {
#include "convolution_1x1s1d1_fp16s.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_fp16a_spv_data[] = {
#include "convolution_1x1s1d1_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack1to4_spv_data[] = {
#include "convolution_pack1to4.spv.hex.h"
};
static const uint32_t convolution_pack1to4_fp16s_spv_data[] = {
#include "convolution_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack1to4_fp16a_spv_data[] = {
#include "convolution_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_spv_data[] = {
#include "convolution_pack4.spv.hex.h"
};
static const uint32_t convolution_pack4_fp16s_spv_data[] = {
#include "convolution_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_fp16a_spv_data[] = {
#include "convolution_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4to1_spv_data[] = {
#include "convolution_pack4to1.spv.hex.h"
};
static const uint32_t convolution_pack4to1_fp16s_spv_data[] = {
#include "convolution_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4to1_fp16a_spv_data[] = {
#include "convolution_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t crop_spv_data[] = {
#include "crop.spv.hex.h"
};
static const uint32_t crop_fp16s_spv_data[] = {
#include "crop_fp16s.spv.hex.h"
};
static const uint32_t crop_fp16a_spv_data[] = {
#include "crop_fp16a.spv.hex.h"
};
static const uint32_t crop_pack4_spv_data[] = {
#include "crop_pack4.spv.hex.h"
};
static const uint32_t crop_pack4_fp16s_spv_data[] = {
#include "crop_pack4_fp16s.spv.hex.h"
};
static const uint32_t crop_pack4_fp16a_spv_data[] = {
#include "crop_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_spv_data[] = {
#include "deconvolution.spv.hex.h"
};
static const uint32_t deconvolution_fp16s_spv_data[] = {
#include "deconvolution_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_fp16a_spv_data[] = {
#include "deconvolution_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_spv_data[] = {
#include "deconvolution_pack1to4.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_fp16s_spv_data[] = {
#include "deconvolution_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_fp16a_spv_data[] = {
#include "deconvolution_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack4_spv_data[] = {
#include "deconvolution_pack4.spv.hex.h"
};
static const uint32_t deconvolution_pack4_fp16s_spv_data[] = {
#include "deconvolution_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack4_fp16a_spv_data[] = {
#include "deconvolution_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_spv_data[] = {
#include "deconvolution_pack4to1.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_fp16s_spv_data[] = {
#include "deconvolution_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_fp16a_spv_data[] = {
#include "deconvolution_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t dropout_spv_data[] = {
#include "dropout.spv.hex.h"
};
static const uint32_t dropout_fp16s_spv_data[] = {
#include "dropout_fp16s.spv.hex.h"
};
static const uint32_t dropout_fp16a_spv_data[] = {
#include "dropout_fp16a.spv.hex.h"
};
static const uint32_t dropout_pack4_spv_data[] = {
#include "dropout_pack4.spv.hex.h"
};
static const uint32_t dropout_pack4_fp16s_spv_data[] = {
#include "dropout_pack4_fp16s.spv.hex.h"
};
static const uint32_t dropout_pack4_fp16a_spv_data[] = {
#include "dropout_pack4_fp16a.spv.hex.h"
};
static const uint32_t eltwise_spv_data[] = {
#include "eltwise.spv.hex.h"
};
static const uint32_t eltwise_fp16s_spv_data[] = {
#include "eltwise_fp16s.spv.hex.h"
};
static const uint32_t eltwise_fp16a_spv_data[] = {
#include "eltwise_fp16a.spv.hex.h"
};
static const uint32_t eltwise_pack4_spv_data[] = {
#include "eltwise_pack4.spv.hex.h"
};
static const uint32_t eltwise_pack4_fp16s_spv_data[] = {
#include "eltwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t eltwise_pack4_fp16a_spv_data[] = {
#include "eltwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t flatten_spv_data[] = {
#include "flatten.spv.hex.h"
};
static const uint32_t flatten_fp16s_spv_data[] = {
#include "flatten_fp16s.spv.hex.h"
};
static const uint32_t flatten_fp16a_spv_data[] = {
#include "flatten_fp16a.spv.hex.h"
};
static const uint32_t flatten_pack4_spv_data[] = {
#include "flatten_pack4.spv.hex.h"
};
static const uint32_t flatten_pack4_fp16s_spv_data[] = {
#include "flatten_pack4_fp16s.spv.hex.h"
};
static const uint32_t flatten_pack4_fp16a_spv_data[] = {
#include "flatten_pack4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_spv_data[] = {
#include "innerproduct.spv.hex.h"
};
static const uint32_t innerproduct_fp16s_spv_data[] = {
#include "innerproduct_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_fp16a_spv_data[] = {
#include "innerproduct_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_spv_data[] = {
#include "innerproduct_pack1to4.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_fp16s_spv_data[] = {
#include "innerproduct_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_fp16a_spv_data[] = {
#include "innerproduct_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack4_spv_data[] = {
#include "innerproduct_pack4.spv.hex.h"
};
static const uint32_t innerproduct_pack4_fp16s_spv_data[] = {
#include "innerproduct_pack4_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack4_fp16a_spv_data[] = {
#include "innerproduct_pack4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_spv_data[] = {
#include "innerproduct_pack4to1.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_fp16s_spv_data[] = {
#include "innerproduct_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_fp16a_spv_data[] = {
#include "innerproduct_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_spv_data[] = {
#include "lrn_norm.spv.hex.h"
};
static const uint32_t lrn_norm_fp16s_spv_data[] = {
#include "lrn_norm_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_fp16a_spv_data[] = {
#include "lrn_norm_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_spv_data[] = {
#include "lrn_norm_across_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_fp16s_spv_data[] = {
#include "lrn_norm_across_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_fp16a_spv_data[] = {
#include "lrn_norm_across_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_spv_data[] = {
#include "lrn_norm_within_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_fp16s_spv_data[] = {
#include "lrn_norm_within_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_fp16a_spv_data[] = {
#include "lrn_norm_within_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_spv_data[] = {
#include "lrn_square_pad.spv.hex.h"
};
static const uint32_t lrn_square_pad_fp16s_spv_data[] = {
#include "lrn_square_pad_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_fp16a_spv_data[] = {
#include "lrn_square_pad_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_spv_data[] = {
#include "lrn_square_pad_across_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_fp16s_spv_data[] = {
#include "lrn_square_pad_across_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_fp16a_spv_data[] = {
#include "lrn_square_pad_across_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_spv_data[] = {
#include "lrn_square_pad_within_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_fp16s_spv_data[] = {
#include "lrn_square_pad_within_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_fp16a_spv_data[] = {
#include "lrn_square_pad_within_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t pooling_spv_data[] = {
#include "pooling.spv.hex.h"
};
static const uint32_t pooling_fp16s_spv_data[] = {
#include "pooling_fp16s.spv.hex.h"
};
static const uint32_t pooling_fp16a_spv_data[] = {
#include "pooling_fp16a.spv.hex.h"
};
static const uint32_t pooling_global_spv_data[] = {
#include "pooling_global.spv.hex.h"
};
static const uint32_t pooling_global_fp16s_spv_data[] = {
#include "pooling_global_fp16s.spv.hex.h"
};
static const uint32_t pooling_global_fp16a_spv_data[] = {
#include "pooling_global_fp16a.spv.hex.h"
};
static const uint32_t pooling_global_pack4_spv_data[] = {
#include "pooling_global_pack4.spv.hex.h"
};
static const uint32_t pooling_global_pack4_fp16s_spv_data[] = {
#include "pooling_global_pack4_fp16s.spv.hex.h"
};
static const uint32_t pooling_global_pack4_fp16a_spv_data[] = {
#include "pooling_global_pack4_fp16a.spv.hex.h"
};
static const uint32_t pooling_pack4_spv_data[] = {
#include "pooling_pack4.spv.hex.h"
};
static const uint32_t pooling_pack4_fp16s_spv_data[] = {
#include "pooling_pack4_fp16s.spv.hex.h"
};
static const uint32_t pooling_pack4_fp16a_spv_data[] = {
#include "pooling_pack4_fp16a.spv.hex.h"
};
static const uint32_t prelu_spv_data[] = {
#include "prelu.spv.hex.h"
};
static const uint32_t prelu_fp16s_spv_data[] = {
#include "prelu_fp16s.spv.hex.h"
};
static const uint32_t prelu_fp16a_spv_data[] = {
#include "prelu_fp16a.spv.hex.h"
};
static const uint32_t prelu_pack4_spv_data[] = {
#include "prelu_pack4.spv.hex.h"
};
static const uint32_t prelu_pack4_fp16s_spv_data[] = {
#include "prelu_pack4_fp16s.spv.hex.h"
};
static const uint32_t prelu_pack4_fp16a_spv_data[] = {
#include "prelu_pack4_fp16a.spv.hex.h"
};
static const uint32_t relu_spv_data[] = {
#include "relu.spv.hex.h"
};
static const uint32_t relu_fp16s_spv_data[] = {
#include "relu_fp16s.spv.hex.h"
};
static const uint32_t relu_fp16a_spv_data[] = {
#include "relu_fp16a.spv.hex.h"
};
static const uint32_t relu_pack4_spv_data[] = {
#include "relu_pack4.spv.hex.h"
};
static const uint32_t relu_pack4_fp16s_spv_data[] = {
#include "relu_pack4_fp16s.spv.hex.h"
};
static const uint32_t relu_pack4_fp16a_spv_data[] = {
#include "relu_pack4_fp16a.spv.hex.h"
};
static const uint32_t reshape_spv_data[] = {
#include "reshape.spv.hex.h"
};
static const uint32_t reshape_fp16s_spv_data[] = {
#include "reshape_fp16s.spv.hex.h"
};
static const uint32_t reshape_fp16a_spv_data[] = {
#include "reshape_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack1to4_spv_data[] = {
#include "reshape_pack1to4.spv.hex.h"
};
static const uint32_t reshape_pack1to4_fp16s_spv_data[] = {
#include "reshape_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack1to4_fp16a_spv_data[] = {
#include "reshape_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack4_spv_data[] = {
#include "reshape_pack4.spv.hex.h"
};
static const uint32_t reshape_pack4_fp16s_spv_data[] = {
#include "reshape_pack4_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack4_fp16a_spv_data[] = {
#include "reshape_pack4_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack4to1_spv_data[] = {
#include "reshape_pack4to1.spv.hex.h"
};
static const uint32_t reshape_pack4to1_fp16s_spv_data[] = {
#include "reshape_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack4to1_fp16a_spv_data[] = {
#include "reshape_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t scale_spv_data[] = {
#include "scale.spv.hex.h"
};
static const uint32_t scale_fp16s_spv_data[] = {
#include "scale_fp16s.spv.hex.h"
};
static const uint32_t scale_fp16a_spv_data[] = {
#include "scale_fp16a.spv.hex.h"
};
static const uint32_t scale_pack4_spv_data[] = {
#include "scale_pack4.spv.hex.h"
};
static const uint32_t scale_pack4_fp16s_spv_data[] = {
#include "scale_pack4_fp16s.spv.hex.h"
};
static const uint32_t scale_pack4_fp16a_spv_data[] = {
#include "scale_pack4_fp16a.spv.hex.h"
};
static const uint32_t sigmoid_spv_data[] = {
#include "sigmoid.spv.hex.h"
};
static const uint32_t sigmoid_fp16s_spv_data[] = {
#include "sigmoid_fp16s.spv.hex.h"
};
static const uint32_t sigmoid_fp16a_spv_data[] = {
#include "sigmoid_fp16a.spv.hex.h"
};
static const uint32_t sigmoid_pack4_spv_data[] = {
#include "sigmoid_pack4.spv.hex.h"
};
static const uint32_t sigmoid_pack4_fp16s_spv_data[] = {
#include "sigmoid_pack4_fp16s.spv.hex.h"
};
static const uint32_t sigmoid_pack4_fp16a_spv_data[] = {
#include "sigmoid_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_div_sum_spv_data[] = {
#include "softmax_div_sum.spv.hex.h"
};
static const uint32_t softmax_div_sum_fp16s_spv_data[] = {
#include "softmax_div_sum_fp16s.spv.hex.h"
};
static const uint32_t softmax_div_sum_fp16a_spv_data[] = {
#include "softmax_div_sum_fp16a.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_spv_data[] = {
#include "softmax_div_sum_pack4.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_fp16s_spv_data[] = {
#include "softmax_div_sum_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_fp16a_spv_data[] = {
#include "softmax_div_sum_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_spv_data[] = {
#include "softmax_exp_sub_max.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_fp16s_spv_data[] = {
#include "softmax_exp_sub_max_fp16s.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_fp16a_spv_data[] = {
#include "softmax_exp_sub_max_fp16a.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_spv_data[] = {
#include "softmax_exp_sub_max_pack4.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_fp16s_spv_data[] = {
#include "softmax_exp_sub_max_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_fp16a_spv_data[] = {
#include "softmax_exp_sub_max_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_max_spv_data[] = {
#include "softmax_reduce_max.spv.hex.h"
};
static const uint32_t softmax_reduce_max_fp16s_spv_data[] = {
#include "softmax_reduce_max_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_max_fp16a_spv_data[] = {
#include "softmax_reduce_max_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_spv_data[] = {
#include "softmax_reduce_max_pack4.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_fp16s_spv_data[] = {
#include "softmax_reduce_max_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_fp16a_spv_data[] = {
#include "softmax_reduce_max_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_spv_data[] = {
#include "softmax_reduce_sum.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_fp16s_spv_data[] = {
#include "softmax_reduce_sum_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_fp16a_spv_data[] = {
#include "softmax_reduce_sum_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_spv_data[] = {
#include "softmax_reduce_sum_pack4.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_fp16s_spv_data[] = {
#include "softmax_reduce_sum_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_fp16a_spv_data[] = {
#include "softmax_reduce_sum_pack4_fp16a.spv.hex.h"
};
static const uint32_t tanh_spv_data[] = {
#include "tanh.spv.hex.h"
};
static const uint32_t tanh_fp16s_spv_data[] = {
#include "tanh_fp16s.spv.hex.h"
};
static const uint32_t tanh_fp16a_spv_data[] = {
#include "tanh_fp16a.spv.hex.h"
};
static const uint32_t tanh_pack4_spv_data[] = {
#include "tanh_pack4.spv.hex.h"
};
static const uint32_t tanh_pack4_fp16s_spv_data[] = {
#include "tanh_pack4_fp16s.spv.hex.h"
};
static const uint32_t tanh_pack4_fp16a_spv_data[] = {
#include "tanh_pack4_fp16a.spv.hex.h"
};
static const uint32_t binaryop_spv_data[] = {
#include "binaryop.spv.hex.h"
};
static const uint32_t binaryop_fp16s_spv_data[] = {
#include "binaryop_fp16s.spv.hex.h"
};
static const uint32_t binaryop_fp16a_spv_data[] = {
#include "binaryop_fp16a.spv.hex.h"
};
static const uint32_t binaryop_pack4_spv_data[] = {
#include "binaryop_pack4.spv.hex.h"
};
static const uint32_t binaryop_pack4_fp16s_spv_data[] = {
#include "binaryop_pack4_fp16s.spv.hex.h"
};
static const uint32_t binaryop_pack4_fp16a_spv_data[] = {
#include "binaryop_pack4_fp16a.spv.hex.h"
};
static const uint32_t unaryop_spv_data[] = {
#include "unaryop.spv.hex.h"
};
static const uint32_t unaryop_fp16s_spv_data[] = {
#include "unaryop_fp16s.spv.hex.h"
};
static const uint32_t unaryop_fp16a_spv_data[] = {
#include "unaryop_fp16a.spv.hex.h"
};
static const uint32_t unaryop_pack4_spv_data[] = {
#include "unaryop_pack4.spv.hex.h"
};
static const uint32_t unaryop_pack4_fp16s_spv_data[] = {
#include "unaryop_pack4_fp16s.spv.hex.h"
};
static const uint32_t unaryop_pack4_fp16a_spv_data[] = {
#include "unaryop_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_spv_data[] = {
#include "convolutiondepthwise.spv.hex.h"
};
static const uint32_t convolutiondepthwise_fp16s_spv_data[] = {
#include "convolutiondepthwise_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_fp16a_spv_data[] = {
#include "convolutiondepthwise_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_spv_data[] = {
#include "convolutiondepthwise_group.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_fp16s_spv_data[] = {
#include "convolutiondepthwise_group_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_fp16a_spv_data[] = {
#include "convolutiondepthwise_group_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_spv_data[] = {
#include "convolutiondepthwise_group_pack1to4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_fp16s_spv_data[] = {
#include "convolutiondepthwise_group_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_fp16a_spv_data[] = {
#include "convolutiondepthwise_group_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_spv_data[] = {
#include "convolutiondepthwise_group_pack4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_fp16s_spv_data[] = {
#include "convolutiondepthwise_group_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_fp16a_spv_data[] = {
#include "convolutiondepthwise_group_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_spv_data[] = {
#include "convolutiondepthwise_group_pack4to1.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_fp16s_spv_data[] = {
#include "convolutiondepthwise_group_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_fp16a_spv_data[] = {
#include "convolutiondepthwise_group_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_spv_data[] = {
#include "convolutiondepthwise_pack4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_fp16s_spv_data[] = {
#include "convolutiondepthwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_fp16a_spv_data[] = {
#include "convolutiondepthwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t padding_spv_data[] = {
#include "padding.spv.hex.h"
};
static const uint32_t padding_fp16s_spv_data[] = {
#include "padding_fp16s.spv.hex.h"
};
static const uint32_t padding_fp16a_spv_data[] = {
#include "padding_fp16a.spv.hex.h"
};
static const uint32_t padding_pack4_spv_data[] = {
#include "padding_pack4.spv.hex.h"
};
static const uint32_t padding_pack4_fp16s_spv_data[] = {
#include "padding_pack4_fp16s.spv.hex.h"
};
static const uint32_t padding_pack4_fp16a_spv_data[] = {
#include "padding_pack4_fp16a.spv.hex.h"
};
static const uint32_t permute_spv_data[] = {
#include "permute.spv.hex.h"
};
static const uint32_t permute_fp16s_spv_data[] = {
#include "permute_fp16s.spv.hex.h"
};
static const uint32_t permute_fp16a_spv_data[] = {
#include "permute_fp16a.spv.hex.h"
};
static const uint32_t permute_pack4to1_spv_data[] = {
#include "permute_pack4to1.spv.hex.h"
};
static const uint32_t permute_pack4to1_fp16s_spv_data[] = {
#include "permute_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t permute_pack4to1_fp16a_spv_data[] = {
#include "permute_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t priorbox_spv_data[] = {
#include "priorbox.spv.hex.h"
};
static const uint32_t priorbox_fp16s_spv_data[] = {
#include "priorbox_fp16s.spv.hex.h"
};
static const uint32_t priorbox_fp16a_spv_data[] = {
#include "priorbox_fp16a.spv.hex.h"
};
static const uint32_t priorbox_mxnet_spv_data[] = {
#include "priorbox_mxnet.spv.hex.h"
};
static const uint32_t priorbox_mxnet_fp16s_spv_data[] = {
#include "priorbox_mxnet_fp16s.spv.hex.h"
};
static const uint32_t priorbox_mxnet_fp16a_spv_data[] = {
#include "priorbox_mxnet_fp16a.spv.hex.h"
};
static const uint32_t interp_spv_data[] = {
#include "interp.spv.hex.h"
};
static const uint32_t interp_fp16s_spv_data[] = {
#include "interp_fp16s.spv.hex.h"
};
static const uint32_t interp_fp16a_spv_data[] = {
#include "interp_fp16a.spv.hex.h"
};
static const uint32_t interp_pack4_spv_data[] = {
#include "interp_pack4.spv.hex.h"
};
static const uint32_t interp_pack4_fp16s_spv_data[] = {
#include "interp_pack4_fp16s.spv.hex.h"
};
static const uint32_t interp_pack4_fp16a_spv_data[] = {
#include "interp_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_spv_data[] = {
#include "deconvolutiondepthwise.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_spv_data[] = {
#include "deconvolutiondepthwise_group.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_group_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_group_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_spv_data[] = {
#include "deconvolutiondepthwise_group_pack1to4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_group_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_group_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4to1.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_group_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_spv_data[] = {
#include "deconvolutiondepthwise_pack4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_fp16s_spv_data[] = {
#include "deconvolutiondepthwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_fp16a_spv_data[] = {
#include "deconvolutiondepthwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t shufflechannel_spv_data[] = {
#include "shufflechannel.spv.hex.h"
};
static const uint32_t shufflechannel_fp16s_spv_data[] = {
#include "shufflechannel_fp16s.spv.hex.h"
};
static const uint32_t shufflechannel_fp16a_spv_data[] = {
#include "shufflechannel_fp16a.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_spv_data[] = {
#include "shufflechannel_pack4.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_fp16s_spv_data[] = {
#include "shufflechannel_pack4_fp16s.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_fp16a_spv_data[] = {
#include "shufflechannel_pack4_fp16a.spv.hex.h"
};
static const uint32_t clip_spv_data[] = {
#include "clip.spv.hex.h"
};
static const uint32_t clip_fp16s_spv_data[] = {
#include "clip_fp16s.spv.hex.h"
};
static const uint32_t clip_fp16a_spv_data[] = {
#include "clip_fp16a.spv.hex.h"
};
static const uint32_t clip_pack4_spv_data[] = {
#include "clip_pack4.spv.hex.h"
};
static const uint32_t clip_pack4_fp16s_spv_data[] = {
#include "clip_pack4_fp16s.spv.hex.h"
};
static const uint32_t clip_pack4_fp16a_spv_data[] = {
#include "clip_pack4_fp16a.spv.hex.h"
};
static const uint32_t reorg_spv_data[] = {
#include "reorg.spv.hex.h"
};
static const uint32_t reorg_fp16s_spv_data[] = {
#include "reorg_fp16s.spv.hex.h"
};
static const uint32_t reorg_fp16a_spv_data[] = {
#include "reorg_fp16a.spv.hex.h"
};
static const uint32_t reorg_pack1to4_spv_data[] = {
#include "reorg_pack1to4.spv.hex.h"
};
static const uint32_t reorg_pack1to4_fp16s_spv_data[] = {
#include "reorg_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t reorg_pack1to4_fp16a_spv_data[] = {
#include "reorg_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t reorg_pack4_spv_data[] = {
#include "reorg_pack4.spv.hex.h"
};
static const uint32_t reorg_pack4_fp16s_spv_data[] = {
#include "reorg_pack4_fp16s.spv.hex.h"
};
static const uint32_t reorg_pack4_fp16a_spv_data[] = {
#include "reorg_pack4_fp16a.spv.hex.h"
};
static const uint32_t packing_1to4_spv_data[] = {
#include "packing_1to4.spv.hex.h"
};
static const uint32_t packing_1to4_fp16s_spv_data[] = {
#include "packing_1to4_fp16s.spv.hex.h"
};
static const uint32_t packing_1to4_fp16a_spv_data[] = {
#include "packing_1to4_fp16a.spv.hex.h"
};
static const uint32_t packing_4to1_spv_data[] = {
#include "packing_4to1.spv.hex.h"
};
static const uint32_t packing_4to1_fp16s_spv_data[] = {
#include "packing_4to1_fp16s.spv.hex.h"
};
static const uint32_t packing_4to1_fp16a_spv_data[] = {
#include "packing_4to1_fp16a.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_spv_data[] = {
#include "cast_fp16_to_fp32.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_fp16s_spv_data[] = {
#include "cast_fp16_to_fp32_fp16s.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_fp16a_spv_data[] = {
#include "cast_fp16_to_fp32_fp16a.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_spv_data[] = {
#include "cast_fp16_to_fp32_pack4.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_fp16s_spv_data[] = {
#include "cast_fp16_to_fp32_pack4_fp16s.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_fp16a_spv_data[] = {
#include "cast_fp16_to_fp32_pack4_fp16a.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_spv_data[] = {
#include "cast_fp32_to_fp16.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_fp16s_spv_data[] = {
#include "cast_fp32_to_fp16_fp16s.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_fp16a_spv_data[] = {
#include "cast_fp32_to_fp16_fp16a.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_spv_data[] = {
#include "cast_fp32_to_fp16_pack4.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_fp16s_spv_data[] = {
#include "cast_fp32_to_fp16_pack4_fp16s.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_fp16a_spv_data[] = {
#include "cast_fp32_to_fp16_pack4_fp16a.spv.hex.h"
};


